### PR TITLE
IBM-255: Consitency & Style of Expected In & Expected Out & Expected outgoing

### PR DESCRIPTION
**Pull request by cksanders**
https://jira.digital.homeoffice.gov.uk/browse/IBM-255

### CODE REVIEW

**Comment by chrisns** [comment]
We made a very explicit decision to render the content how it currently for semantic markup reasons.
Doing this will put cid id's under a column heading that doesn't apply to them, and it stops being a table of data.

**Comment by cksanders** [comment]
The expected display of nested data has changed (IBM-255). Subtitles of nested data are not required. Consistent with the implementation of Beds OOC, where there is no title. Thus, I replicated the choice of implementation (previously approved and on master) of Beds OOC (IBM-86).

Additional benefits received form removing the ul li implementation and adding an additional tr are related to improving readability, reuse of code, & (marginal) reduced pageload time:
- reduced amount of DOM elements
- reduced amount of css seelctors
- consistency, simplicity, and reusability of e2e test steps & feature tests.
- consistency of nested elements in the centreGender html file

**Comment by chrisns** [comment]
While I agree with most of that.
My point however is that the data is fundamentally not the same format as the other data in the table, it is a list of CIDs as opposed to a breakdown of detail that fits the existing table headings.
The column heading you're proposing putting a cid id under in this PR is 'Category' which is not semantically valid

**Comment by cksanders** [comment]
'Category' definition (http://www.dictionary.com/browse/category) :
"1. any general or comprehensive division; a class.
2. a classificatory division in any field of knowledge, as a phylum or any of its subdivisions in biology."

I would suggest (with reference to the definition above), that a cid number is equivalent to a task force, as they are both a division of things, where each has a particular shared characteristic.

**Comment by chrisns** [comment]
You're really reaching. A CID 'person id' which refers to an individual human being is not a category or division of things unless you're to dealing on a biological or atomic level, which we aren't.

Furthermore it is fundamentally different in nature to all the other categories in the table which refer to a collection of individuals
.
Your motivation is apparently simplifying markup, sometimes however when you have a table of data, and an unordered list of things that are loosely connected it is correct to semantically have them as such.
To put cids in the table would result in you using a table for the sake of layout, which would be a misuse of a table.
Furthermore your approach would make it incredibly confusing to navigate with a screen reader or similar accessibility device.
Therefore I'm closing this PR.
I would suggest that if you want to fulfil the original of this ticket to write some sass and leave the markup as is. - Though i'm not personally convinced that it's actually a valid thing to work on anyway, and will happily challenge the requirement.

**Pull request closed without merging**
